import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Lazy-initialize GoogleGenAI to handle errors gracefully if key is missing on startup
let aiInstance: GoogleGenAI | null = null;
function getGemini(): GoogleGenAI {
  const key = process.env.GEMINI_API_KEY;
  if (!key) {
    throw new Error("GEMINI_API_KEY environment variable is required. Please set it in Settings -> Secrets.");
  }
  if (!aiInstance) {
    aiInstance = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build"
        }
      }
    });
  }
  return aiInstance;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // API Route for the Forge Hermes Agentic RAG
  app.post("/api/gemini/agent", async (req, res) => {
    try {
      const {
        message,
        history = [],
        ragContext = "",
        temperature = 0.2,
        accuracyGuard = true,
        webSearch = true,
        ingestedRepos = []
      } = req.body;

      if (!message) {
        return res.status(400).json({ error: "Missing prompt message" });
      }

      const ai = getGemini();

      // Formulate a powerful developer instruction matching Galyons kitchen theme + RAG / Hermes principles
      let systemInstruction = `You are HERMES, the Agentic RAG Co-Pilot for the FORGE OPERATING SYSTEM. 
You think like a premium technical chef-advisor, combining the strict technical authority of Galyons culinary laws with agentic intelligence (inspired by NousResearch Hermes-Agent and NVIDIA Web-Search RAG).

GOALS & DOCTRINE DEFINITION:
1. Ground your answers inside the Galyons System Core Laws (6-item rule, 20 scale prep, 6x6 MEP) and any specifications/recipes provided in the local context.
2. If asked about wider culinary knowledge or external systems, use Search Grounding if enabled to fetch official data and verify.
3. Be extremely precise, concise, and professional. Respond in straightforward, authoritative, and structured Chef-de-Partie terms. Avoid fluff or praise.

RAG PARAMETERS IN USE:
- Ingested Sources: ${ingestedRepos.length > 0 ? ingestedRepos.map((r: any) => `"${r}"`).join(", ") : "Local FORGE database only"}.
- Accuracy Guard Status: ${accuracyGuard ? "ACTIVE (STRICT NON-HALLUCINATION)" : "INACTIVE"}.
- Web Search Status: ${webSearch ? "ACTIVE (REAL-TIME GOOGLE GROUNDING)" : "INACTIVE"}.

LOCAL CORE SPEC CONTEXT:
${ragContext}

INSTRUCTIONS FOR THE CONVERSATION:
- Answer the user's prompt by integrating Galyons doctrine with your general agent intelligence.
- If Accuracy Guard is ACTIVE: You MUST reject hallucination. If a specific weight, temperature, or rule is not explicitly provided in the local context or verified via Search, state that it is not defined rather than inventing it.
- If Web Search is ACTIVE: Provide factual answers backed by Google Search Grounding and ensure sources can be cleanly cited.`;

      const gContents = [];
      
      // Load history in correct Gemini format
      if (history && history.length > 0) {
        for (const h of history) {
          gContents.push({
            role: h.role === "user" ? "user" : "model",
            parts: [{ text: h.text }]
          });
        }
      }

      // Add the final user query
      gContents.push({
        role: "user",
        parts: [{ text: message }]
      });

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: gContents,
        config: {
          systemInstruction,
          temperature,
          tools: webSearch ? [{ googleSearch: {} }] : []
        }
      });

      const text = response.text || "No response generated by JEMMA/HERMES.";
      
      // Extract grounding metadata sources
      const dbChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
      const sources = dbChunks.map((chunk: any) => {
        if (chunk.web) {
          return {
            title: chunk.web.title || "Search Grounding Source",
            uri: chunk.web.uri
          };
        }
        return null;
      }).filter(Boolean);

      return res.json({
        text,
        sources
      });

    } catch (error: any) {
      console.error("Gemini Agent API Error:", error);
      return res.status(500).json({
        error: error.message || "An error occurred inside the JEMMA/HERMES connection."
      });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
